[tool.ruff]
line-length = 160
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.ruff.lint]
select = [
    # ruff
    "RUF",
    # pycodestyle
    "E", "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-print
    "T",
    # flake8-todos
    "TD",
    # flake8-logging
    "LOG",
    # pep8-naming
    "N",
    # pydocstyle
    "D",
    # flake8-return
    "RET",
    # flake8-type-checking
    "TYP",
    # pylint
    "PL",
]
ignore = [
    "D100", # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D415", # First line should end with a period
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D400", # First line should end with a period
    "TD003", # Missing issue link on the line following
    "PLR0913", # Too many arguments
]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
